# Generated by Django 5.1.7 on 2025-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('image', models.ImageField(upload_to='phases/')),
                ('object_x', models.PositiveIntegerField()),
                ('object_y', models.PositiveIntegerField()),
                ('tolerance', models.PositiveIntegerField(default=50)),
            ],
        ),
    ]
